#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression --message="Restoring files..." --weight=5
ynh_restore_file --origin_path="$install_dir"
ynh_restore_file --origin_path="$data_dir"
ynh_restore_file --origin_path="/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_restore_file --origin_path="/etc/systemd/system/$app.service"

chown -R "$app:www-data" "$install_dir"
chown -R "$app:www-data" "$data_dir"

mkdir -p "/var/log/$app"
chown -R "$app:$app" "/var/log/$app"

systemctl daemon-reload
systemctl enable "$app.service" --quiet

yunohost service add "$app" \
    --description="Elastos Runtime (serve + room gateway)" \
    --log="/var/log/$app/$app.log"

ynh_systemd_action --service_name="$app" --action="restart" \
    --log_path="/var/log/$app/$app.log" \
    --line_match="room gateway listening"
ynh_systemd_action --service_name=nginx --action=reload

ynh_script_progression --message="Elastos Runtime restored." --last
